---
x-shared_setting: &shared_settings
  image: debian:11
  # Other shared properties here

services:
  service-a:
    <<: *shared_settings
    environment:
      - SERVICE=a
  service-b:
    <<: *shared_settings
    environment:
      - SERVICE=b
